const types = {
    ORDER_PLACED: 'ORDER PLACED',
    ORDER_STARTED: 'ORDER STARTED',
    ORDER_COMPLETED: 'ORDER COMPLETED',
    PAYMENT_CLEARED: 'PAYMENT CLEARED',
    PAYMENT_MADE: 'PAYMENT MADE',
}

export default types
